name: publish to github registry
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kyuuseiryuu'
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
